config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'items/index'
  root 'home#index' 
  get 'home/profil'
  post 'home/profil'
  resources :items
  resources :carts
  resources :cart_items
  resources :places do
    resources :comments
  end
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items
  
    def add_one(cart_item)
      cart_item.quantity += 1
      cart_item.save
    end
  
    def remove_one(cart_item)
      cart_item.quantity -= 1
      cart_item.save
    end
  
    def total_price
      tot = 0.00
      cart_items.each do |cart_item|
        tot += cart_item.item.price.to_f * cart_item.quantity
      end
      return tot
    end
  
    def count_items
      nb_items = 0
      cart_items.each do |cart_item|
        nb_items += cart_item.quantity
      end
      return nb_items
    end
  
  end
  

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart
  end
  

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true
    validates :image_url, presence: true
  
    has_many :cart_items
    has_many :item_orders
    has_many :carts, through: :cart_items
  
    has_one_attached :picture
    
  
    has_many :orders, through: :item_orders
  
  
  end
  

app/models/item_order.rb
class ItemOrder < ApplicationRecord
    belongs_to :item
    belongs_to :order
  end
  

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :item_orders
    has_many :items, through: :item_orders
  
    def total_price()
      tot = 0.00
      items.each do |item|
        tot += item.price.to_d
      end
      return tot
    end
  end
  

app/models/place.rb
class Place < ApplicationRecord
    has_one_attached :image
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart

  has_many :orders
  has_one :picture
  has_many :comments
  after_create :create_cart

  def create_cart
    cart = Cart.new
    cart.user = self
    cart.save
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def show()
      @cart = current_user.cart
    end
  
  end
  

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    @order = Order.create!(user_id: current_user.id)
    current_user.cart.items.each do |item|
      @order.items << item
    end

    current_user.cart.items.clear
    @current_email = current_user.email
    ForestMailer.welcome_email(current_user.email,@order).deliver_now
    @amount = 500
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken])
      charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Cat pics',
      :currency    => 'eur')
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to :root
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
  
      @items = Item.all
  
  
    end
  
    def show
    end
  
    def update
    
         @item= Item.find(params[:id])
         @item.picture.attach(params[:item][:picture])
         redirect_to "/"
      
    end
  end
  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  # GET /places
  # GET /places.json
  def index
   if user_signed_in?
    @places = Place.all
    @meteo = Meteo.new
   else 
    redirect_to home_index_path
  end
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @comments = Comment.all
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    @place.image.purge
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
    puts params
      params.require(:place).permit(:name, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/confirmation_helper.rb
module ConfirmationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<!------ Include the above in your HEAD tag ---------->
<div class="panier">
<% current_user.cart.cart_items.each do |cart_item| %>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-10 col-md-offset-1">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th class="text-center">Price</th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="col-sm-8 col-md-6">
                        <div class="media">
                            <a class="thumbnail pull-left" href="#"> <img class="media-object" src="<%= cart_item.item.image_url %>" style="width: 72px; height: 72px;"> </a>
                            <div class="media-body">
                                <h4><%= cart_item.item.title %></a></h4>
                                <h5>by: <%= current_user.name %></a></h5>
                                <span>Status: </span><span class="text-success"><strong>In Stock</strong></span>                            </div>
                        </div></td>
                        <td class="col-sm-1 col-md-1" style="text-align: center">
                            x <%= cart_item.quantity %>
                        </td>
                        <td class="col-sm-1 col-md-1 text-center"><strong><span class="badge badge-info"><%= number_to_currency(cart_item.item.price, unit: "$", separator: ",", format: "%n %u") %></strong></td>
                        <td class="col-sm-1 col-md-1">
                        <%= link_to "delete", cart_item_path(:id => cart_item), :method=>:delete, class: "buttonn"%>
                       </td>
                        
                       
                        
                    </tr>
<% end %>
                    <tr>
                        
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td><h5>Subtotal</h5></td>
                        <td class="text-right"><h5><strong>
                        <p class="font-weight-bold"><span class="badge badge-info"><%= number_to_currency(current_user.cart.total_price, unit: "$", separator: ",", format: "%n %u") %></span></p>
                        </strong></h5></td>
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td><h3>Total</h3></td>
                        <td class="text-right"><h3><strong><p class="font-weight-bold"><span class="badge badge-info"><%= number_to_currency(current_user.cart.total_price, unit: "$", separator: ",", format: "%n %u") %></span></p>                        </strong></h3></td>
                    </tr>
                    <tr>
                        <td>   </td>
                        <td>   </td>
                        <td>   </td>
                        <td>
                        <td>
                        <%= form_tag charges_path do %>
                            <article>
                              <% if flash[:error].present? %>
                                <div id="error_explanation">
                                  <p><%= flash[:error] %></p>
                                </div>
                              <% end %>
                             
                            </article>
                          
                            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                                    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                                    data-amount="<%=current_user.cart.total_price * 100%>"
                                    data-locale="auto">
                                     </script>
                          <% end %>
                          </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>

app/views/home/index.html.erb
<!doctype html>



<html class="no-js" lang="zxx">
<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">window.dojoRequire(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us19.list-manage.com","uuid":"2d0f2ea92762c6a3d44dff5d9","lid":"f590ae3890","uniqueMethods":true}) })</script>      

    <!--Mainmenu-area/-->

   

    <!--Header-area-->
    <body class="header-area overlay full-height relative v-center" id="home-page">
        <div class="absolute anlge-bg"></div>
        <div class="container">
            <div class="row v-center">
                <div class="col-xs-12 col-md-7 header-text">
                    <h2>Bienvenue dans notre site.</h2>
                    <p>Vous trouverez les meilleurs endroits de Lyon et ses alentours, afin de vous ressourcer et vous promener en forêt.</p>
                </div>               
            </div>
        </div>
    
   

    

</body>

</html>

app/views/items/index.html.erb
<div class = "item">
    <% @items.sort.each do |product| %>
        <div class= "col-md-4">
          <figure class="snip1195">
            <h4><%=product.title%></h4>
              <div class="image">
                <img src="<%=product.image_url%>" alt="sq-sample14" />
              </div>
              <div class="rating">
                <i class="ion-ios-star"></i><i class="ion-ios-star"></i><i class="ion-ios-star"></i><i class="ion-ios-star"></i><i class="ion-ios-star-outline"></i>
              </div>
            <figcaption>
              <p>
                <%= product.description%></li>
              </p>
              <div class="price">
                <span class="product_price"><s>$29.00</s><%=product.price%>$</span>
              </div>
           <% if user_signed_in? %>
              <%= button_to "Add to cart", cart_items_path(:id => product),class: "add-to-cart" %>
           <% end %>
           </figure>
        </div>
    <% end %>
</div>  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="menu.js"></script>