config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'items/index'
  root 'home#index' 
  get 'home/profil'
  post 'home/profil'
  resources :items
  resources :carts
  resources :cart_items
  resources :places do
    resources :comments
  end
  devise_for :users
  resources :charges
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

    belongs_to :user
    has_many :cart_items
    has_many :items, through: :cart_items
  
    def add_one(cart_item)
      cart_item.quantity += 1
      cart_item.save
    end
  
    def remove_one(cart_item)
      cart_item.quantity -= 1
      cart_item.save
    end
  
    def total_price
      tot = 0.00
      cart_items.each do |cart_item|
        tot += cart_item.item.price.to_f * cart_item.quantity
      end
      return tot
    end
  
    def count_items
      nb_items = 0
      cart_items.each do |cart_item|
        nb_items += cart_item.quantity
      end
      return nb_items
    end
  
  end
  

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :cart
  end
  

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true
    validates :image_url, presence: true
  
    has_many :cart_items
    has_many :item_orders
    has_many :carts, through: :cart_items
  
    has_one_attached :picture
    
  
    has_many :orders, through: :item_orders
  
  
  end
  

app/models/item_order.rb
class ItemOrder < ApplicationRecord
    belongs_to :item
    belongs_to :order
  end
  

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :user
    has_many :item_orders
    has_many :items, through: :item_orders
  
    def total_price()
      tot = 0.00
      items.each do |item|
        tot += item.price.to_d
      end
      return tot
    end
  end
  

app/models/place.rb
class Place < ApplicationRecord
    has_one_attached :image
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart

  has_many :orders
  has_one :picture
  has_many :comments
  after_create :create_cart

  def create_cart
    cart = Cart.new
    cart.user = self
    cart.save
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def show()
      @cart = current_user.cart
    end
  
  end
  

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
  
      @items = Item.all
  
  
    end
  
    def show
    end
  
    def update
    
         @item= Item.find(params[:id])
         @item.picture.attach(params[:item][:picture])
         redirect_to "/"
      
    end
  end
  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/confirmation_helper.rb
module ConfirmationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<head>
<meta charset="utf-8">
<meta name="author" content="John Doe">
<meta name="description" content="">
<meta name="keywords" content="HTML,CSS,XML,JavaScript">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- Title -->
<title>T-box</title>

</head>

<body data-spy="scroll" data-target="#primary-menu">

<div >
	<div class="sk-folding-cube">
		<div class="sk-cube1 sk-cube"></div>
		<div class="sk-cube2 sk-cube"></div>
		<div class="sk-cube4 sk-cube"></div>
		<div class="sk-cube3 sk-cube"></div>
	</div>
</div>
<!--Mainmenu-area-->
<div class="mainmenu-area" data-spy="affix" data-offset-top="100">
	<div class="container">
		<!--Logo-->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#primary-menu">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>

		
</div>
		<!--Logo/-->
	<nav class="collapse navbar-collapse" id="primary-menu">
		<div class= "teambox">
			<a class="navbar-brand logo">
			<%=image_tag("logo5.png")%>
			</a>
		</div>
			<ul class="nav navbar-nav navbar-right" >
			<li>
				<%= link_to 'Accueil', home_index_path %>
			</li>			
		<% if user_signed_in? %>
			<li>
				<%= link_to 'Se déconnecté', destroy_user_session_path, method: :delete %>
			</li>
			<li>
				<%= link_to 'Mon profil', home_profil_path%>
			</li>
			<li>
				<%= link_to 'Edit son profil', edit_user_registration_path %>
			</li>
			<li>
				<%= link_to 'Box', places_path %>
			</li>
			<li>
				<%= link_to 'Panier', cart_path(current_user.cart.id)%>
			</li> 
		
		<%else%>
			<li>
				<%= link_to 'Se connecté/inscription', new_user_registration_path %>
			</li>  
	
	<% end %>
			</ul>
	</nav>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T-BOX</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="author" content="John Doe">
    <meta name="description" content="">
    <meta name="keywords" content="HTML,CSS,XML,JavaScript">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?key='+Rails.application.credentials.api_key_map %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield(:head_tags) %>
    
    
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>